#!/usr/bin/env python3

import RPi.GPIO as GPIO
import time

motor_pin = 7
trig_pin = 11
echo_pin = 12

def setup():
    GPIO.setmode(GPIO.BOARD)
    GPIO.setup(motor_pin, GPIO.OUT)
    GPIO.setup(trig_pin, GPIO.OUT)
    GPIO.setup(echo_pin, GPIO.IN)


    global motor_pwm
    motor_pwm = GPIO.PWM(motor_pin, 1000)
    motor_pwm.start(0)


def distance():
    GPIO.output(trig_pin, GPIO.LOW)
    time.sleep(0.000001)
    GPIO.output(trig_pin, GPIO.HIGH)
    time.sleep(0.00001)

    while GPIO.input(echo_pin) == 0: #while echo_pin is set to GPIO.LOW
        pass
    time1 = time.time()

    while GPIO.input(echo_pin) == 1: #While echo_pin is set to GPIO.HIGH
        pass

    time2 = time.time()
    duration = time2 - time1
    distance_cm = (duration * 340 / 2) * 100
    return distance_cm

def motor_on(intensity, sleep_time):
        motor_pwm.ChangeDutyCycle(intensity)
        time.sleep(sleep_time)
        motor_pwm.ChangeDutyCycle(0)
        time.sleep(sleep_time)

def motor_off():
    motor_pwm.ChangeDutyCycle(0)

def loop():
    while True:
        dis = distance()
        if dis is None:
            continue

        if dis <= 275:
            motor_on(50, 0.2)
        elif dis <=600:
            motor_on(50, 0.5)
        else:
            motor_pwm.ChangeDutyCycle(0)
            time.sleep(0.1)


if __name__ == "__main__":
    setup()
    try:
        loop()
    except KeyboardInterrupt:
        GPIO.cleanup()

